n = input('Digite algo: ')
print(f'Isso é um numero? {n.isalnum()}')
print(f'Isso é uma letra? {n.isalpha()}')
print(f'Isso é um ASCII? {n.isascii()}')
print(f'Isso é um digito de (0 a 9)? {n.isdigit()}')
print(f'Isso está minusculo? {n.islower()}')
print(f'Isso é um decimal? {n.isdecimal()}')
print(f'Isso é um identificador? {n.isidentifier()}')
print(f'Isso é um número? {n.isnumeric()}')
print(f'Isso é imprimível? {n.isprintable()}')
print(f'Isso tem espaço? {n.isspace()}')
print(f'Isso é um título? {n.istitle()}')
print(f'Isso está maiúsculo? {n.isupper()}')
